ALTER TABLE "Order" ADD COLUMN IF NOT EXISTS "otpCode" TEXT;
ALTER TABLE "Order" ADD COLUMN IF NOT EXISTS "otpVerified" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "Order" ADD COLUMN IF NOT EXISTS "otpAttempts" INTEGER NOT NULL DEFAULT 0;
