ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "whatsappCredits" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "Shop" ADD COLUMN IF NOT EXISTS "notificationChannel" TEXT NOT NULL DEFAULT 'sms';
ALTER TYPE "CreditType" ADD VALUE IF NOT EXISTS 'WHATSAPP_PURCHASE';
